/**
 * @package jQuery Country-State Select Plugin
 * @author Justen Robertson <justen@justenrobertson.com>
 * @version 0.1a
 * @license GPL
 *
 * Creates paired country/state select boxes. The state box will update with
 * appropriate states/provinces for the selected country. Requires
 * jQuery.doubleSelect.
 *
 */

(function($){
	jQuery.fn.countryState = function(second, options) {

	var countries = {
		"Afghanistan":{"key":"AF","values":{"N/A":"N/A"}},
		"Albania":{"key":"AL","values":{"N/A":"N/A"}},
		"Algeria":{"key":"DZ","values":{"N/A":"N/A"}},
		"American Samoa":{"key":"AS","values":{"N/A":"N/A"}},
		"Andorra":{"key":"AD","values":{"N/A":"N/A"}},
		"Angola":{"key":"AO","values":{"N/A":"N/A"}},
		"Anguilla":{"key":"AI","values":{"N/A":"N/A"}},
		"Antarctica":{"key":"AQ","values":{"N/A":"N/A"}},
		"Antigua and Barbuda":{"key":"AG","values":{"N/A":"N/A"}},
		"Argentina":{"key":"AR","values":{"N/A":"N/A"}},
		"Armenia":{"key":"AM","values":{"N/A":"N/A"}},
		"Aruba":{"key":"AW","values":{"N/A":"N/A"}},
		"Australia": {
			"key":"AU",
			"values": {
				"Australian Antarctic Territory":"AAT",
				"Australian Capital Territory":"ACT",
				"Northern Territory":"NT",
				"New South Wales":"NSW",
				"Queensland":"QLD",
				"South Australia":"SA",
				"Tasmania":"TAS",
				"Victoria":"VIC",
				"Western Australia":"WA"
			}
		},
		"Austria":{"key":"AT","values":{"N/A":"N/A"}},
		"Azerbaijan":{"key":"AZ","values":{"N/A":"N/A"}},
		"Azores":{"key":"AP","values":{"N/A":"N/A"}},
		"Bahamas":{"key":"BS","values":{"N/A":"N/A"}},
		"Bahrain":{"key":"BH","values":{"N/A":"N/A"}},
		"Bangladesh":{"key":"BD","values":{"N/A":"N/A"}},
		"Barbados":{"key":"BB","values":{"N/A":"N/A"}},
		"Belarus":{"key":"BY","values":{"N/A":"N/A"}},
		"Belgium":{"key":"BE","values":{"N/A":"N/A"}},
		"Belize":{"key":"BZ","values":{"N/A":"N/A"}},
		"Benin":{"key":"BJ","values":{"N/A":"N/A"}},
		"Bermuda":{"key":"BM","values":{"N/A":"N/A"}},
		"Bhutan":{"key":"BT","values":{"N/A":"N/A"}},
		"Bolivia":{"key":"BO","values":{"N/A":"N/A"}},
		"Bosnia And Herzegowina":{"key":"BA","values":{"N/A":"N/A"}},
		"Bosnia-Herzegovina":{"key":"XB","values":{"N/A":"N/A"}},
		"Botswana":{"key":"BW","values":{"N/A":"N/A"}},
		"Bouvet Island":{"key":"BV","values":{"N/A":"N/A"}},
		"Brazil":{
			"key":"BR",
			"values":{
				"Acre":"AC",
				"Alagoas":"AL",
				"Amazonas":"AM",
				"Amapa":"AP",
				"Baia":"BA",
				"Ceara":"CE",
				"Distrito Federal":"DF",
				"Espirito Santo":"ES",
				"Fernando de Noronha":"FN",
				"Goias":"GO",
				"Maranhao":"MA",
				"Minas Gerais":"MG",
				"Mato Grosso do Sul":"MS",
				"Mato Grosso":"MT",
				"Para":"PA",
				"Paraiba":"PB",
				"Pernambuco":"PE",
				"Piaui":"PI",
				"Parana":"PR",
				"Rio de Janeiro":"RJ",
				"Rio Grande do Norte":"RN",
				"Rondonia":"RO",
				"Roraima":"RR",
				"Rio Grande do Sul":"RS",
				"Santa Catarina":"SC",
				"Sergipe":"SE",
				"Sao Paulo":"SP",
				"Tocatins":"TO"
			}
		},
		"British Indian Ocean Territory":{"key":"IO","values":{"N/A":"N/A"}},
		"British Virgin Islands":{"key":"VG","values":{"N/A":"N/A"}},
		"Brunei Darussalam":{"key":"BN","values":{"N/A":"N/A"}},
		"Bulgaria":{"key":"BG","values":{"N/A":"N/A"}},
		"Burkina Faso":{"key":"BF","values":{"N/A":"N/A"}},
		"Burundi":{"key":"BI","values":{"N/A":"N/A"}},
		"Cambodia":{"key":"KH","values":{"N/A":"N/A"}},
		"Cameroon":{"key":"CM","values":{"N/A":"N/A"}},
		"Canada": {
			"key":"CA",
			"values":{
				"Alberta":"AB",
				"Manitoba":"MB",
				"British Columbia":"BC",
				"New Brunswick":"NB",
				"Newfoundland and Labrador":"Netherlands",
				"Nova Scotia":"NS",
				"Northwest Territories":"NT",
				"Nunavut":"NU",
				"Ontario":"ON",
				"Prince Edward Island":"PE",
				"Quebec":"QC",
				"Saskatchewan":"SK",
				"Yukon Territory":"YT"
			}
		},
		"Cape Verde":{"key":"CV","values":{"N/A":"N/A"}},
		"Cayman Islands":{"key":"KY","values":{"N/A":"N/A"}},
		"Central African Republic":{"key":"CF","values":{"N/A":"N/A"}},
		"Chad":{"key":"TD","values":{"N/A":"N/A"}},
		"Chile":{"key":"CL","values":{"N/A":"N/A"}},
		"China":{"key":"CN","values":{"N/A":"N/A"}},
		"Christmas Island":{"key":"CX","values":{"N/A":"N/A"}},
		"Cocos (Keeling) Islands":{"key":"CC","values":{"N/A":"N/A"}},
		"Colombia":{"key":"CO","values":{"N/A":"N/A"}},
		"Comoros":{"key":"KM","values":{"N/A":"N/A"}},
		"Congo":{"key":"CG","values":{"N/A":"N/A"}},
		"Congo, The Democratic Republic O":{"key":"CD","values":{"N/A":"N/A"}},
		"Cook Islands":{"key":"CK","values":{"N/A":"N/A"}},
		"Corsica":{"key":"XE","values":{"N/A":"N/A"}},
		"Costa Rica":{"key":"CR","values":{"N/A":"N/A"}},
		"Cote d` Ivoire (Ivory Coast)":{"key":"CI","values":{"N/A":"N/A"}},
		"Croatia":{"key":"HR","values":{"N/A":"N/A"}},
		"Cuba":{"key":"CU","values":{"N/A":"N/A"}},
		"Cyprus":{"key":"CY","values":{"N/A":"N/A"}},
		"Czech Republic":{"key":"CZ","values":{"N/A":"N/A"}},
		"Denmark":{"key":"DK","values":{"N/A":"N/A"}},
		"Djibouti":{"key":"DJ","values":{"N/A":"N/A"}},
		"Dominica":{"key":"DM","values":{"N/A":"N/A"}},
		"Dominican Republic":{"key":"DO","values":{"N/A":"N/A"}},
		"East Timor":{"key":"TP","values":{"N/A":"N/A"}},
		"Ecuador":{"key":"EC","values":{"N/A":"N/A"}},
		"Egypt":{"key":"EG","values":{"N/A":"N/A"}},
		"El Salvador":{"key":"SV","values":{"N/A":"N/A"}},
		"Equatorial Guinea":{"key":"GQ","values":{"N/A":"N/A"}},
		"Eritrea":{"key":"ER","values":{"N/A":"N/A"}},
		"Estonia":{"key":"EE","values":{"N/A":"N/A"}},
		"Ethiopia":{"key":"ET","values":{"N/A":"N/A"}},
		"Falkland Islands (Malvinas)":{"key":"FK","values":{"N/A":"N/A"}},
		"Faroe Islands":{"key":"FO","values":{"N/A":"N/A"}},
		"Fiji":{"key":"FJ","values":{"N/A":"N/A"}},
		"Finland":{"key":"FI","values":{"N/A":"N/A"}},
		"France (Includes Monaco)":{"key":"FR","values":{"N/A":"N/A"}},
		"France, Metropolitan":{"key":"FX","values":{"N/A":"N/A"}},
		"French Guiana":{"key":"GF","values":{"N/A":"N/A"}},
		"French Polynesia":{"key":"PF","values":{"N/A":"N/A"}},
		"French Polynesia (Tahiti)":{"key":"TA","values":{"N/A":"N/A"}},
		"French Southern Territories":{"key":"TF","values":{"N/A":"N/A"}},
		"Gabon":{"key":"GA","values":{"N/A":"N/A"}},
		"Gambia":{"key":"GM","values":{"N/A":"N/A"}},
		"Georgia":{"key":"GE","values":{"N/A":"N/A"}},
		"Germany":{"key":"DE","values":{"N/A":"N/A"}},
		"Ghana":{"key":"GH","values":{"N/A":"N/A"}},
		"Gibraltar":{"key":"GI","values":{"N/A":"N/A"}},
		"Greece":{"key":"GR","values":{"N/A":"N/A"}},
		"Greenland":{"key":"GL","values":{"N/A":"N/A"}},
		"Grenada":{"key":"GD","values":{"N/A":"N/A"}},
		"Guadeloupe":{"key":"GP","values":{"N/A":"N/A"}},
		"Guam":{"key":"GU","values":{"N/A":"N/A"}},
		"Guatemala":{"key":"GT","values":{"N/A":"N/A"}},
		"Guinea":{"key":"GN","values":{"N/A":"N/A"}},
		"Guinea-Bissau":{"key":"GW","values":{"N/A":"N/A"}},
		"Guyana":{"key":"GY","values":{"N/A":"N/A"}},
		"Haiti":{"key":"HT","values":{"N/A":"N/A"}},
		"Heard And Mc Donald Islands":{"key":"HM","values":{"N/A":"N/A"}},
		"Holy See (Vatican City State)":{"key":"VA","values":{"N/A":"N/A"}},
		"Honduras":{"key":"HN","values":{"N/A":"N/A"}},
		"Hong Kong":{"key":"HK","values":{"N/A":"N/A"}},
		"Hungary":{"key":"HU","values":{"N/A":"N/A"}},
		"Iceland":{"key":"IS","values":{"N/A":"N/A"}},
		"India":{"key":"IN","values":{"N/A":"N/A"}},
		"Indonesia":{"key":"ID","values":{"N/A":"N/A"}},
		"Iran":{"key":"IR","values":{"N/A":"N/A"}},
		"Iraq":{"key":"IQ","values":{"N/A":"N/A"}},
		"Ireland (Eire)":{
			"key":"IE",
			"values":{
				"County Antrim":"CO ANTRIM",
				"County Armagh":"CO ARMAGH",
				"County Down":"CO DOWN",
				"County Fermanagh":"CO FERMANAGH",
				"County Londonderry":"CO DERRY",
				"County Tyrone":"CO TYRONE",
				"County Cavan":"CO CAVAN",
				"County Donegal":"CO DONEGAL",
				"County Monaghan":"CO MONAGHAN",
				"County Dublin":"CO DUBLIN",
				"County Carlow":"CO CARLOW",
				"County Kildare":"CO KILDARE",
				"County Kilkenny":"CO KILKENNY",
				"County Laois":"CO LAOIS",
				"County Longford":"CO LONGFORD",
				"County Louth":"CO LOUTH",
				"County Meath":"CO MEATH",
				"County Offaly":"CO OFFALY",
				"County Westmeath":"CO WESTMEATH",
				"County Wexford":"CO WEXFORD",
				"County Wicklow":"CO WICKLOW",
				"County Galway":"CO GALWAY",
				"County Mayo":"CO MAYO",
				"County Leitrim":"CO LEITRIM",
				"County Roscommon":"CO ROSCOMMON",
				"County Sligo":"CO SLIGO",
				"County Clare":"CO CLARE",
				"County Cork":"CO CORK",
				"County Kerry":"CO KERRY",
				"County Limerick":"CO LIMERICK",
				"County Tipperary":"CO TIPPERARY",
				"County Waterford":"CO WATERFORD"
			}
		},
		"Israel":{"key":"IL","values":{"N/A":"N/A"}},
		"Italy":{"key":"IT","values":{"N/A":"N/A"}},
		"Jamaica":{"key":"JM","values":{"N/A":"N/A"}},
		"Japan":{"key":"JP","values":{"N/A":"N/A"}},
		"Jordan":{"key":"JO","values":{"N/A":"N/A"}},
		"Kazakhstan":{"key":"KZ","values":{"N/A":"N/A"}},
		"Kenya":{"key":"KE","values":{"N/A":"N/A"}},
		"Kiribati":{"key":"KI","values":{"N/A":"N/A"}},
		"Korea, Democratic People\'S Repub":{"key":"KP","values":{"N/A":"N/A"}},
		"Kuwait":{"key":"KW","values":{"N/A":"N/A"}},
		"Kyrgyzstan":{"key":"KG","values":{"N/A":"N/A"}},
		"Laos":{"key":"LA","values":{"N/A":"N/A"}},
		"Latvia":{"key":"LV","values":{"N/A":"N/A"}},
		"Lebanon":{"key":"LB","values":{"N/A":"N/A"}},
		"Lesotho":{"key":"LS","values":{"N/A":"N/A"}},
		"Liberia":{"key":"LR","values":{"N/A":"N/A"}},
		"Libya":{"key":"LY","values":{"N/A":"N/A"}},
		"Liechtenstein":{"key":"LI","values":{"N/A":"N/A"}},
		"Lithuania":{"key":"LT","values":{"N/A":"N/A"}},
		"Luxembourg":{"key":"LU","values":{"N/A":"N/A"}},
		"Macao":{"key":"MO","values":{"N/A":"N/A"}},
		"Macedonia":{"key":"MK","values":{"N/A":"N/A"}},
		"Madagascar":{"key":"MG","values":{"N/A":"N/A"}},
		"Madeira Islands":{"key":"ME","values":{"N/A":"N/A"}},
		"Malawi":{"key":"MW","values":{"N/A":"N/A"}},
		"Malaysia":{"key":"MY","values":{"N/A":"N/A"}},
		"Maldives":{"key":"MV","values":{"N/A":"N/A"}},
		"Mali":{"key":"ML","values":{"N/A":"N/A"}},
		"Malta":{"key":"MT","values":{"N/A":"N/A"}},
		"Marshall Islands":{"key":"MH","values":{"N/A":"N/A"}},
		"Martinique":{"key":"MQ","values":{"N/A":"N/A"}},
		"Mauritania":{"key":"MR","values":{"N/A":"N/A"}},
		"Mauritius":{"key":"MU","values":{"N/A":"N/A"}},
		"Mayotte":{"key":"YT","values":{"N/A":"N/A"}},
		"Mexico":{"key":"MX","values":{"N/A":"N/A"}},
		"Micronesia, Federated States Of":{"key":"FM","values":{"N/A":"N/A"}},
		"Moldova, Republic Of":{"key":"MD","values":{"N/A":"N/A"}},
		"Monaco":{"key":"MC","values":{"N/A":"N/A"}},
		"Mongolia":{"key":"MN","values":{"N/A":"N/A"}},
		"Montserrat":{"key":"MS","values":{"N/A":"N/A"}},
		"Morocco":{"key":"MA","values":{"N/A":"N/A"}},
		"Mozambique":{"key":"MZ","values":{"N/A":"N/A"}},
		"Myanmar (Burma)":{"key":"MM","values":{"N/A":"N/A"}},
		"Namibia":{"key":"NA","values":{"N/A":"N/A"}},
		"Nauru":{"key":"NR","values":{"N/A":"N/A"}},
		"Nepal":{"key":"NP","values":{"N/A":"N/A"}},
		"Netherlands":{
			"key":"NL",
			"values":{
				"Drente":"DR",
				"Flevoland":"FL",
				"Friesland":"FR",
				"Gelderland":"GL",
				"Groningen":"GR",
				"Limburg":"LB",
				"Noord Brabant":"NB",
				"Noord Holland":"NH",
				"Overijssel":"OV",
				"Utrecht":"UT",
				"Zuid Holland":"ZH",
				"Zeeland":"ZL"
			}
		},
		"Netherlands Antilles":{"key":"AN","values":{"N/A":"N/A"}},
		"New Caledonia":{"key":"NC","values":{"N/A":"N/A"}},
		"New Zealand":{"key":"NZ","values":{"N/A":"N/A"}},
		"Nicaragua":{"key":"NI","values":{"N/A":"N/A"}},
		"Niger":{"key":"NE","values":{"N/A":"N/A"}},
		"Nigeria":{"key":"NG","values":{"N/A":"N/A"}},
		"Niue":{"key":"NU","values":{"N/A":"N/A"}},
		"Norfolk Island":{"key":"NF","values":{"N/A":"N/A"}},
		"Northern Mariana Islands":{"key":"MP","values":{"N/A":"N/A"}},
		"Norway":{"key":"NO","values":{"N/A":"N/A"}},
		"Oman":{"key":"OM","values":{"N/A":"N/A"}},
		"Pakistan":{"key":"PK","values":{"N/A":"N/A"}},
		"Palau":{"key":"PW","values":{"N/A":"N/A"}},
		"Palestinian Territory, Occupied":{"key":"PS","values":{"N/A":"N/A"}},
		"Panama":{"key":"PA","values":{"N/A":"N/A"}},
		"Papua New Guinea":{"key":"PG","values":{"N/A":"N/A"}},
		"Paraguay":{"key":"PY","values":{"N/A":"N/A"}},
		"Peru":{"key":"PE","values":{"N/A":"N/A"}},
		"Philippines":{"key":"PH","values":{"N/A":"N/A"}},
		"Pitcairn":{"key":"PN","values":{"N/A":"N/A"}},
		"Poland":{"key":"PL","values":{"N/A":"N/A"}},
		"Portugal":{"key":"PT","values":{"N/A":"N/A"}},
		"Puerto Rico":{"key":"PR","values":{"N/A":"N/A"}},
		"Qatar":{"key":"QA","values":{"N/A":"N/A"}},
		"Reunion":{"key":"RE","values":{"N/A":"N/A"}},
		"Romania":{"key":"RO","values":{"N/A":"N/A"}},
		"Russian Federation":{"key":"RU","values":{"N/A":"N/A"}},
		"Rwanda":{"key":"RW","values":{"N/A":"N/A"}},
		"Saint Kitts And Nevis":{"key":"KN","values":{"N/A":"N/A"}},
		"San Marino":{"key":"SM","values":{"N/A":"N/A"}},
		"Sao Tome and Principe":{"key":"ST","values":{"N/A":"N/A"}},
		"Saudi Arabia":{"key":"SA","values":{"N/A":"N/A"}},
		"Senegal":{"key":"SN","values":{"N/A":"N/A"}},
		"Serbia-Montenegro":{"key":"XS","values":{"N/A":"N/A"}},
		"Seychelles":{"key":"SC","values":{"N/A":"N/A"}},
		"Sierra Leone":{"key":"SL","values":{"N/A":"N/A"}},
		"Singapore":{"key":"SG","values":{"N/A":"N/A"}},
		"Slovak Republic":{"key":"SK","values":{"N/A":"N/A"}},
		"Slovenia":{"key":"SI","values":{"N/A":"N/A"}},
		"Solomon Islands":{"key":"SB","values":{"N/A":"N/A"}},
		"Somalia":{"key":"SO","values":{"N/A":"N/A"}},
		"South Africa":{"key":"ZA","values":{"N/A":"N/A"}},
		"South Georgia And The South Sand":{"key":"GS","values":{"N/A":"N/A"}},
		"South Korea":{"key":"KR","values":{"N/A":"N/A"}},
		"Spain":{"key":"ES","values":{"N/A":"N/A"}},
		"Sri Lanka":{"key":"LK","values":{"N/A":"N/A"}},
		"St. Christopher and Nevis":{"key":"NV","values":{"N/A":"N/A"}},
		"St. Helena":{"key":"SH","values":{"N/A":"N/A"}},
		"St. Lucia":{"key":"LC","values":{"N/A":"N/A"}},
		"St. Pierre and Miquelon":{"key":"PM","values":{"N/A":"N/A"}},
		"St. Vincent and the Grenadines":{"key":"VC","values":{"N/A":"N/A"}},
		"Sudan":{"key":"SD","values":{"N/A":"N/A"}},
		"Suriname":{"key":"SR","values":{"N/A":"N/A"}},
		"Svalbard And Jan Mayen Islands":{"key":"SJ","values":{"N/A":"N/A"}},
		"Swaziland":{"key":"SZ","values":{"N/A":"N/A"}},
		"Sweden":{"key":"SE","values":{"N/A":"N/A"}},
		"Switzerland":{"key":"CH","values":{"N/A":"N/A"}},
		"Syrian Arab Republic":{"key":"SY","values":{"N/A":"N/A"}},
		"Taiwan":{"key":"TW","values":{"N/A":"N/A"}},
		"Tajikistan":{"key":"TJ","values":{"N/A":"N/A"}},
		"Tanzania":{"key":"TZ","values":{"N/A":"N/A"}},
		"Thailand":{"key":"TH","values":{"N/A":"N/A"}},
		"Togo":{"key":"TG","values":{"N/A":"N/A"}},
		"Tokelau":{"key":"TK","values":{"N/A":"N/A"}},
		"Tonga":{"key":"TO","values":{"N/A":"N/A"}},
		"Trinidad and Tobago":{"key":"TT","values":{"N/A":"N/A"}},
		"Tristan da Cunha":{"key":"XU","values":{"N/A":"N/A"}},
		"Tunisia":{"key":"TN","values":{"N/A":"N/A"}},
		"Turkey":{"key":"TR","values":{"N/A":"N/A"}},
		"Turkmenistan":{"key":"TM","values":{"N/A":"N/A"}},
		"Turks and Caicos Islands":{"key":"TC","values":{"N/A":"N/A"}},
		"Tuvalu":{"key":"TV","values":{"N/A":"N/A"}},
		"Uganda":{"key":"UG","values":{"N/A":"N/A"}},
		"Ukraine":{"key":"UA","values":{"N/A":"N/A"}},
		"United Arab Emirates":{"key":"AE","values":{"N/A":"N/A"}},
		"United Kingdom":{
			"key":"UK",
			"values":{
				"Avon":"AVON",
				"Bedfordshire":"BEDS",
				"Berkshire":"BERKS",
				"Buckinghamshire":"BUCKS",
				"Cambridgeshire":"CAMBS",
				"Cheshire":"CHESH",
				"Cleveland":"CLEVE",
				"Cornwall":"CORN",
				"Cumbria":"CUMB",
				"Derbyshire":"DERBY",
				"Devon":"DEVON",
				"Dorset":"DORSET",
				"Durham":"DURHAM",
				"Essex":"ESSEX",
				"Gloucestershire":"GLOUS",
				"Greater London":"GLONDON",
				"Greater Manchester":"GMANCH",
				"Hampshire":"HANTS",
				"Hereford & Worcestershire":"HERWOR",
				"Hertfordshire":"HERTS",
				"Humberside":"HUMBER",
				"Isle of Man":"IOM",
				"Isle of Wight":"IOW",
				"Kent":"KENT",
				"Lancashire":"LANCS",
				"Leicestershire":"LEICS",
				"Lincolnshire":"LINCS",
				"Merseyside":"MERSEY",
				"Norfolk":"NORF",
				"Northamptonshire":"NHANTS",
				"Northumberland":"NTHUMB",
				"Nottinghamshire":"NOTTS",
				"Oxfordshire":"OXON",
				"Shropshire":"SHROPS",
				"Somerset":"SOM",
				"Staffordshire":"STAFFS",
				"Suffolk":"SUFF",
				"Surrey":"SURREY",
				"Sussex":"SUSS",
				"Warwickshire":"WARKS",
				"West Midlands":"WMID",
				"Wiltshire":"WILTS",
				"Yorkshire":"YORK"
			}
		},
		"Great Britain":{"key":"GB","values":{"N/A":"N/A"}},
		"United States": {
			"key":"US",
			"values": {
				"Alaska":"AK",
				"Alabama":"AL",
				"American Samoa":"AS",
				"Arkansas":"AR",
				"Arizona":"AZ",
				"California":"CA",
				"Colorado":"CO",
				"Connecticut":"CT",
				"D.C.":"DC",
				"Delaware":"DE",
				"Florida":"FL",
				"Georgia":"GA",
				"Guam":"GU",
				"Hawaii":"HI",
				"Iowa":"IA",
				"Idaho":"ID",
				"Illinois":"IL",
				"Indiana":"IN",
				"Kansas":"KS",
				"Kentucky":"KY",
				"Louisiana":"LA",
				"Massachusetts":"MA",
				"Maryland":"MD",
				"Maine":"ME",
				"Marianas":"MP",
				"Marshall Islands":"MH",
				"Michigan":"MI",
				"Micronesia":"FM",
				"Minnesota":"MN",
				"Missouri":"MO",
				"Mississippi":"MS",
				"Montana":"MT",
				"North Carolina":"NC",
				"North Dakota":"ND",
				"Nebraska":"NE",
				"New Hampshire":"NH",
				"New Jersey":"NJ",
				"New Mexico":"NM",
				"Nevada":"NV",
				"New York":"NY",
				"Ohio":"OH",
				"Oklahoma":"OK",
				"Oregon":"OR",
				"Palau":"PW",
				"Pennsylvania":"PA",
				"Puerto Rico":"PR",
				"Rhode Island":"RI",
				"South Carolina":"SC",
				"South Dakota":"SD",
				"Tennessee":"TN",
				"Texas":"TX",
				"Utah":"UT",
				"Virginia":"VA",
				"Virgin Islands":"VI",
				"Vermont":"VT",
				"Washington":"WA",
				"Wisconsin":"WI",
				"West Virginia":"WV",
				"Wyoming":"WY",
				"Military Americas":"AA",
				"Military Europe/ME/CA":"AE",
				"Military Pacific":"AP"
			}
		},
		"United States Minor Outlying Isl":{"key":"UM","values":{"N/A":"N/A"}},
		"Uruguay":{"key":"UY","values":{"N/A":"N/A"}},
		"Uzbekistan":{"key":"UZ","values":{"N/A":"N/A"}},
		"Vanuatu":{"key":"VU","values":{"N/A":"N/A"}},
		"Vatican City":{"key":"XV","values":{"N/A":"N/A"}},
		"Venezuela":{"key":"VE","values":{"N/A":"N/A"}},
		"Vietnam":{"key":"VN","values":{"N/A":"N/A"}},
		"Virgin Islands (U.S.)":{"key":"VI","values":{"N/A":"N/A"}},
		"Wallis and Furuna Islands":{"key":"WF","values":{"N/A":"N/A"}},
		"Western Sahara":{"key":"EH","values":{"N/A":"N/A"}},
		"Western Samoa":{"key":"WS","values":{"N/A":"N/A"}},
		"Yemen":{"key":"YE","values":{"N/A":"N/A"}},
		"Yugoslavia":{"key":"YU","values":{"N/A":"N/A"}},
		"Zaire":{"key":"ZR","values":{"N/A":"N/A"}},
		"Zambia":{"key":"ZM","values":{"N/A":"N/A"}},
		"Zimbabwe":{"key":"ZW","values":{"N/A":"N/A"}}
	};
		options = jQuery.extend(options, options);

		/* programmatically add empty option to applicable countries */
		if(options.emptyOption) {
			for(country in countries) {
				if(countries[country].values && !countries[country].values['N/A']) {
					var empty = {};
					empty[options.emptyValue] = options.emptyKey;
					countries[country].values = $.extend(empty, countries[country].values);
				}
			}
		}

		/**
		 * If a full country / state is supplied let's convert it to country code
		 */
		if(options.preselectFirst) {
			if(countries[options.preselectFirst]) {
				options.preselectFirst = countries[options.preselectFirst].key;
			}
		}
		if(options.preselectSecond) {
			for(country in countries) {
				if(countries[country].values[options.preselectFirst]) {
					options.preselectFirst = countries[country].values[options.preselectFirst];
				}
			}
		}

		jQuery(this).doubleSelect(second, countries, options);
	};
})(jQuery);
